apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-event-exporter
  labels:
    k8s-app: kube-event-exporter
spec:
  jobLabel: kube-event-exporter
  selector:
    matchLabels:
      kube-event-exporter: ".*"
  namespaceSelector:
    matchNames:
      - kube-system
      - monitoring
      - default
  endpoints:
    - port: kube-event-exporter
      interval: 5s
